/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package cclin

import (
	"fmt"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/endpoints/request"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	InternalLin = builders.NewInternalResource(
		"lins",
		"Lin",
		func() runtime.Object { return &Lin{} },
		func() runtime.Object { return &LinList{} },
	)
	InternalLinStatus = builders.NewInternalResourceStatus(
		"lins",
		"LinStatus",
		func() runtime.Object { return &Lin{} },
		func() runtime.Object { return &LinList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("cclin.cclin").WithKinds(
		InternalLin,
		InternalLinStatus,
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type Lin struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   LinSpec
	Status LinStatus
}

type LinSpec struct {
}

type LinStatus struct {
}

//
// Lin Functions and Structs
//
// +k8s:deepcopy-gen=false
type LinStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type LinStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type LinList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []Lin
}

func (Lin) NewStatus() interface{} {
	return LinStatus{}
}

func (pc *Lin) GetStatus() interface{} {
	return pc.Status
}

func (pc *Lin) SetStatus(s interface{}) {
	pc.Status = s.(LinStatus)
}

func (pc *Lin) GetSpec() interface{} {
	return pc.Spec
}

func (pc *Lin) SetSpec(s interface{}) {
	pc.Spec = s.(LinSpec)
}

func (pc *Lin) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *Lin) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc Lin) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store Lin.
// +k8s:deepcopy-gen=false
type LinRegistry interface {
	ListLins(ctx request.Context, options *internalversion.ListOptions) (*LinList, error)
	GetLin(ctx request.Context, id string, options *metav1.GetOptions) (*Lin, error)
	CreateLin(ctx request.Context, id *Lin) (*Lin, error)
	UpdateLin(ctx request.Context, id *Lin) (*Lin, error)
	DeleteLin(ctx request.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewLinRegistry(sp builders.StandardStorageProvider) LinRegistry {
	return &storageLin{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageLin struct {
	builders.StandardStorageProvider
}

func (s *storageLin) ListLins(ctx request.Context, options *internalversion.ListOptions) (*LinList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*LinList), err
}

func (s *storageLin) GetLin(ctx request.Context, id string, options *metav1.GetOptions) (*Lin, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*Lin), nil
}

func (s *storageLin) CreateLin(ctx request.Context, object *Lin) (*Lin, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, nil, true)
	if err != nil {
		return nil, err
	}
	return obj.(*Lin), nil
}

func (s *storageLin) UpdateLin(ctx request.Context, object *Lin) (*Lin, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object), nil, nil)
	if err != nil {
		return nil, err
	}
	return obj.(*Lin), nil
}

func (s *storageLin) DeleteLin(ctx request.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil)
	return sync, err
}
